### ISSUE TITLE
Infografía Gestión de proyectos  

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-uzias10#2]
[Gestion de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-uzias10/files/9419907/Gestion.de.proyectos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
Calificacion 20
